server:
  port: 9090
  servlet:
    context-path: /dataSource
spring:
  datasource:
    url: jdbc:mysql://10.88.96.32:3306/bim_platform_home_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
  application:
    name: dataSource
  profiles:
    include: mybatis,mysqldev
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 10GB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  config: classpath:logback-spring.xml

knife4j:
  groupName: 平台门户服务端
  basePackageScan: my.qunz.myDemo